### ISSUE TITLE
Cambio en la pantalla Ingresos / Ofertas

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#13]
Cambiar cada uno de los espacios para que tengan relación con el negocio (líneas 695-735)

**Comment by MarcoChenCu** [comment]
Los cambios en el apartado de 'Ofertas/Ingresos' ya han sido realizados.
![image](https://user-images.githubusercontent.com/116602447/221610787-18cdc1d5-a7bc-4391-9f4a-f5a733664658.png)
