### ISSUE TITLE
Cambiar pantalla Galeria

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#14]
Modificar cada una de las imágenes por unas que tengan relación con el negocio

**Comment by Romeoteni188** [comment]
interado inge.

**Comment by Romeoteni188** [comment]
Listo mi estimado ingenieros las ilustraciones de la galeria ya estan corregidos.
![image](https://user-images.githubusercontent.com/80730726/221466983-6c7259b3-f38e-4f01-b3af-18e9b5b44bd0.png)
