### ISSUE TITLE
Modificar pantalla Personal

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#16]
Registrar a cada uno de los trabajadores, colocando su foto, nombre completo y profesión, a su vez añadir una pequeña frase que los represente (líneas 738-808)

**Comment by alejoca7** [comment]
Buena noche Ingeniero Wilfredo Ac

Se realizo las actualizaciones del personal encargado de la empresa MICOSAS S.A

Adjunto pantallazo del commit:
![image](https://user-images.githubusercontent.com/107315080/221478880-6ef868e2-9674-467b-a757-0b0d2c40cdd4.png)

Adjunto pantallazo de lo realizado
![image](https://user-images.githubusercontent.com/107315080/221479703-024e6841-246b-4c54-9d1f-9cf5996f9d8f.png)
