### ISSUE TITLE
Cambio de la pantalla ¿por que comprar con nosotros?

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#18]
añadir aspectos positivos que destaquen al negocio, y llamen la atencion del cliente 
![image](https://user-images.githubusercontent.com/125329772/221471025-09b23caa-e608-4a93-9108-edcac5287aa0.png)

**Comment by Romeoteni188** [comment]
interado mi estimado inge.

**Comment by Romeoteni188** [comment]
Listo  inge se modifico el widgets del porque comprar con nostros
![image](https://user-images.githubusercontent.com/80730726/221475464-a0d26010-dac1-4c6d-8159-ca140d55083a.png)
