### ISSUE TITLE
Cambiar la paleta de colores del main

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#2]

**Comment by alejoca7** [comment]
Hello Ing Wilfredo Ac

Se realizo la actualizacion de la paleta de colores de Web Micosas

Adjunto log commit 

![image](https://user-images.githubusercontent.com/107315080/221106213-6fadad27-9ff2-42a2-8a0c-a4ca2d2e25e7.png)

Saludos cordiales
