### ISSUE TITLE
Modificar archivo Readme

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#2]
ya se le dieron las instrucciones, modificar lo antes posible

**Comment by Romeoteni188** [comment]
Enterado Inge..!

**Comment by WilfredoAR22** [comment]
Se necesitan los cambios, favor de modificar

**Comment by Romeoteni188** [comment]
Buenas noches inge durante la jornada de ayer tuviron siertos incomendientes laborares , mas sin embargo hasta esta hora se pudo modificar el archivo readme espero su compresion.
![image](https://user-images.githubusercontent.com/80730726/221446422-25d70485-7e7e-4a72-9874-719ee47667e5.png)
