### ISSUE TITLE
Cambio del texto de la pantalla acerca de

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#4]
![image](https://user-images.githubusercontent.com/125329772/221391592-b6ac3401-e051-4254-b342-05a551c7e993.png)

**Comment by bcaal87** [comment]
Veo que aun tienen muchos issues abiertos.

**Comment by WilfredoAR22** [comment]
Buenas noche inge. se realizaron los cambios en la pantalla acerca de
![image](https://user-images.githubusercontent.com/125329772/221462915-ef4650a2-13b4-4403-9a61-2ec9546f36ad.png)
