### ISSUE TITLE
Modificar pantalla home

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#8]
Modificar la pantalla home (líneas 70-87) colocando un título de acuerdo con el negocio y una pequeña descripción de este, a su vez cambiar el video por uno que llame la atención de los clientes

**Comment by MarcoChenCu** [comment]
Buenas noches inge, ya se hicieron los cambios en home. Ya me puede pagar?
![image](https://user-images.githubusercontent.com/116602447/221461188-1dbc63cd-5b5b-41a8-bcc9-6e9308f8a9e9.png)
