### ISSUE TITLE
Modificar el botón “Realizar Cotización”

### ISSUE THREAD

**Issue by WilfredoAR22** [WilfredoAR22/Web_Micosas#9]
Realizar un cambio de aspecto al botón (líneas 810-867) a su vez modificar los mensajes al presionarlo

**Comment by MarcoChenCu** [comment]
Buenas noches ingeniero. Los cambios en el botón 'Cotización' han sido realizados con éxito.
![image](https://user-images.githubusercontent.com/116602447/221475111-342a3bde-fe18-41ac-985c-0a074a246482.png)
